// SPDX-FileCopyrightText: 2024-present Deepstaging
// SPDX-License-Identifier: RPL-1.5

namespace Deepstaging.Projection.Effects.Attributes;

using Attr = CapabilityAttribute;

/// <summary>
/// A queryable wrapper over <see cref="CapabilityAttribute"/> data.
/// Provides strongly-typed access to the target type.
/// </summary>
/// <param name="AttributeData">The underlying Roslyn attribute data.</param>
public sealed record CapabilityAttributeQuery(AttributeData AttributeData) : AttributeQuery(AttributeData)
{
    /// <summary>
    /// Gets whether the target type is resolvable and valid in the current compilation.
    /// Returns <c>false</c> when the target type is generated by another source generator
    /// and not yet available (error type).
    /// </summary>
    public bool HasValidTargetType => ConstructorArg<INamedTypeSymbol>(0)
        .Map(symbol => symbol.AsNamedType())
        .Map(symbol => symbol.IsValid(out _))
        .OrDefault(false);

    /// <summary>
    /// Gets the target type to expose as a runtime capability.
    /// </summary>
    /// <exception cref="InvalidOperationException">Thrown when the target type is not valid.</exception>
    public ValidSymbol<INamedTypeSymbol> TargetType => ConstructorArg<INamedTypeSymbol>(0)
        .Map(symbol => symbol.AsValidNamedType())
        .OrThrow($"{nameof(Attr)} must have a valid target type as its first constructor argument.");
}
